audit_header: false
title: Tracy Real Estate Video Blog with Paul Lopez
description: Our mission at Team Paul Lopez is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Team Paul Lopez, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Paul Lopez
  title:
  license_number: 'DRE #01393330'
  about_markdown: |
    Home sellers and buyers want relationship-building, strategic planning and tough negotiation from the real estate agent they select. Since 2001, I have brought these strengths to my clients and learned a lot about the industry. These big transactions can be an emotional process, and clients are happy to report that I bring the calmness and clarity needed to help them make the best decisions.

    I've helped first-time home buyers and move-up buyers looking for their forever home. I have helped retirees, divorcees and investment buyers, and found a way to bring order to the chaos in every situation. I believe in taking the extra time up front to understand the whole family's needs before creating a plan. Equally important, I'm aligned with a like-minded team that includes inspectors, lenders and title professionals who ensure the process is efficient and painless.
  brand: Team Paul Lopez
  brokerage:
  market: Tracy
  address: 403 W. 11th Street<br>Tracy, CA 95376
  phone: 925-980-0871
  phone_type:
  phone2:
  phone2_type:
  email: Paul@TeamLopez.com
  url: http://teampaullopez.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.teampaullopez.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.teampaullopez.com/map/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.teampaullopez.com/sell/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.teampaullopez.com/map/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/teampaullopez
  linkedin_url: https://www.linkedin.com/in/fplopez/
  youtube_url:
  twitter_url: https://twitter.com/fplopez
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with Paul Lopez'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Team Paul Lopez - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Paul Lopez'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#53185c'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
